### ISSUE TITLE
Run workflows on develop branch

### ISSUE THREAD

**Issue by mneiferbag** [mneiferbag/java-spring-boot#13]
CodeQL and build workflow should run on develop branch as well.

Edit file `.github/workflows/codeql-analysis.yml` section

```
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
```
